### PR TITLE
Zgl cleanup

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
# Description
Add description about what this pull request covers.
- Covers landing page, detail view, and navbar updates
## Number of Fixes
Type of number of fixes included in this PR.

## Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request
#4 #8 
## Problem to Solve
Describe the problem(s) this pull request solves.
- Solves lack of styling for sections of site
## Proposed Changes
Describe the proposed changes.
-Should now see a list of each product type and products on landing page, a product detail page, and navbar should be properly formatted
## Expected Behavior
Describe the expected behavior.
No new behavior
## Steps to Test Solution

1. git fetch
2. runserver
3. login
4. checkout site

## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

## Documentation
[ ] There is new documentation in this pull request that must be reviewed..
[ ] I added documentation for any new classes/methods

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
Now fixed issue with limiting products by product id and showing unit price on order table

**Review by stevenwally — APPROVED** [review]
looking v. fresh :v: 🍌

**Comment by nathantbaker** [comment]
Navbar looks solid, but a few questions:

1. Should the landing page view show at `http://127.0.0.1:8000/` rather than  `http://127.0.0.1:8000/home`? Currently if you go to the homepage of the site, the landing page content doesn't show.
1. The landing page view also doesn't allow me to click and view a product or a category.

**Comment by peterStaggs** [comment]
🍌 Bananerific

**Pull request merged**
